project:
  type: website
  resources: 
    - cv.pdf
    - resume.pdf
    - profile.jpg

website:
  title: "Alexis Adzich"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
    background: secondary
      
  page-footer: 
    right: "&copy; 2024, Alexis Adzich"

format:
  html:
    theme: journal
    css: styles.css
    toc: true 
    
    
execute: 
  freeze: auto



